// Auto-generated from client/public/images.
// Run "npm run prepare:images" after adding or renaming images.
export const images = {
  "logoGold": "/images/logo-gold.svg",
  "logoWhite": "/images/logo-white.svg",
  "navLogoGold": "/images/nav-logo-gold.png",
  "navLogoWhite": "/images/nav-logo-white.png",
  "heroDesert": "/images/hero-desert.webp",
  "heroCity": "/images/hero-city.webp",
  "heroCamp": "/images/hero-camp.webp",
  "heroCamel": "/images/hero-camel.webp",
  "tourQuad": "/images/tour-quad.webp",
  "tourCamp": "/images/tour-camp.webp",
  "tourVip": "/images/tour-vip.webp",
  "tourGate": "/images/tour-gate.webp",
  "tourCamel": "/images/tour-camel.webp",
  "tourCaravan": "/images/tour-private.webp",
  "tourPrivate": "/images/tour-private.webp",
  "cityDubai": "/images/city-01-dubai-burj-al-arab.webp",
  "cityBurj": "/images/city-02-dubai-burj-khalifa.webp",
  "cityAbuDhabi": "/images/city-03-abu-dhabi.webp",
  "citySix": "/images/city-04-six-emirates.webp",
  "cityOldDubai": "/images/city-05-old-dubai.webp",
  "cityCorniche": "/images/city-06-mosque-corniche.webp",
  "adventureBuggy": "/images/adv-buggy.webp",
  "adventureDunes": "/images/adv-dunes.webp",
  "adventureQuad": "/images/adv-quad.webp",
  "adventureEvening": "/images/adv-evening.webp",
  "adventureDrive": "/images/adv-dune-drive.webp",
  "adventureDouble": "/images/adv-double.webp",
  "heliPalm": "/images/heli-palm.webp",
  "heliMarina": "/images/heli-marina.webp",
  "heliVision": "/images/heli-vision.webp",
  "heliPrivate": "/images/heli-private.webp",
  "heliPremium": "/images/heli-premium.webp",
  "attractionBurj": "/images/attr-burj.webp",
  "attractionAquarium": "/images/attr-aquarium.webp",
  "attractionMosque": "/images/attr-mosque.webp",
  "attractionMuseum": "/images/attr-museum.webp",
  "promo": "/images/promo-bg.webp",
  "aboutPrimary": "/images/about-1.webp",
  "aboutSecondary": "/images/about-2.webp",
  "blogOne": "/images/blog-1.webp",
  "blogTwo": "/images/blog-2.webp",
  "blogThree": "/images/blog-3.webp"
}
